"""List headings audited on official finance employer boards."""

EMPLOYERS = {
    "tp_icap": "tp icap",
    "akuna_capital": "akuna capital",
    "maven_securities": "maven securities",
    "point72": "point72",
    "virtu_financial": "virtu financial",
    "tower_research": "tower research capital",
    "old_mission": "old mission",
    "schonfeld": "schonfeld",
    "five_rings": "five rings",
    "hudson_river_trading": "hudson river trading",
    "transmarket_group": "transmarket group",
    "dv_trading": "dv trading",
    "walleye_capital": "walleye capital",
    "squarepoint_capital": "squarepoint capital",
    "chicago_trading": "chicago trading company",
    "chicago_trading_campus": "chicago trading company",
    "belvedere_trading": "belvedere trading",
}
QUALIFICATIONS = {
    "wolverine": {"what we're looking for"},
    "gelber": {"what you'll need", "what we'd like to see"},
    "verition": {"qualifications"},
    "marshall_wace_graduates": {"what we look for"},
    "pimco": {"requirements", "qualifications", "position requirements"},
    "td": {"qualifications"},
    "state_street": {
        "requirements",
        "education and preferred qualifications",
        "desired skills and experience",
    },
    "aquatic": {"candidate requirements", "requirements", "technical requirements"},
    "graviton": {"requirements", "required skills and qualifications", "who we're looking for"},
    "aqr": {"what you'll bring"},
    "winton": {"what we are looking for"},
    "worldquant": {"what you'll bring", "additional preferred qualifications"},
    "g_research": {
        "the ideal candidate will have",
        "the ideal candidate will have the following skills and experience",
    },
    "blackrock": {
        "qualifications, knowledge and experience",
        "skills / knowledge",
        "you have",
    },
    "wells_fargo": {"required qualifications", "desired qualification"},
    "bank_of_america": {
        "required qualifications",
        "desired qualifications",
        "required skills",
        "desired skills",
        "required education, skills and experience",
        "required education, skills, and experience",
        "minimum education requirement",
    },
    "rbc": {
        "must have",
        "must-have",
        "nice-to-have",
        "basic qualifications",
        "other required qualifications",
    },
    "mako": {"what we need from you", "what we're looking for"},
    "geneva_trading": {"the ideal candidate", "what we're looking for", "preferred extras"},
    "da_vinci": {"requirements"},
    "qube_research": {"your present skillset", "your profile", "eligible candidates"},
    "man_group": {
        "skills and qualifications",
        "essential competencies",
        "desired qualifications",
        "technology and business skills",
        "advantageous competencies",
    },
    "totalenergies": {"candidate profile", "qualifications"},
    "engie": {
        "qualifications and experience",
        "candidate profile",
        "what you'll bring",
        "what you’ll bring",
        "your profile as algorithmic trader",
        "your profile as structurer",
    },
    "edf_trading": {
        "requirements and qualifications",
        "requirements",
        "experience required",
        "technical requirements",
    },
    "marex": {"skills and experience"},
    "bp": {"to be eligible for the stands graduate programme you should"},
    "shell": {"what you bring"},
    "tp_icap": {"essential", "desired"},
    "akuna_capital": {
        "qualities that make great candidates",
        "additional qualities that make great candidates",
    },
    "maven_securities": {"key criteria", "key requirements", "who you are"},
    "point72": {"requirements", "requirments", "desirable candidates"},
    "virtu_financial": {"the candidate", "requirements"},
    "tower_research": {"qualifications", "requirements", "preferred qualifications (not required)"},
    "old_mission": {"required skills", "required qualifications", "preferred qualifications"},
    "schonfeld": {"what you need", "required skills and qualifications", "we'd love if you had"},
    "five_rings": {"about you"},
    "hudson_river_trading": {"qualifications", "skills"},
    "transmarket_group": {"requirements"},
    "dv_trading": {"requirements", "requirements：", "preferred skills"},
    "walleye_capital": {"qualifications"},
    "squarepoint_capital": {
        "qualifications",
        "required qualifications",
        "preferred candidate profile",
        "nice to have",
    },
    "chicago_trading": {"what we're looking for", "nice to have", "nice to haves"},
    "chicago_trading_campus": {
        "qualifications",
        "key requirements",
        "what we're looking for",
        "what it takes for you to be successful",
        "nice to have",
    },
    "belvedere_trading": {"what you'll need", "key qualities in great candidates"},
}
RESPONSIBILITIES = {
    "wolverine": {"what you'll do"},
    "gelber": {"what you'll do"},
    "verition": {"responsibilities"},
    "pimco": {"responsibilities"},
    "td": {"roles and responsibilities include"},
    "state_street": {
        "responsibilities",
        "as a junior trader, you will",
        "as an efx quant analyst you will",
    },
    "graviton": {"responsibilities", "key responsibilities", "what you'll work on"},
    "aqr": {"your role"},
    "winton": {"your responsibilities will include"},
    "worldquant": {"the role", "key responsibilities"},
    "g_research": {"the role"},
    "blackrock": {"key responsibilities", "responsibilities", "your responsibilities"},
    "wells_fargo": {"in this role, you will"},
    "bank_of_america": {"responsibilities", "key responsibilities"},
    "rbc": {"what will you do?", "what will you do ?", "principle responsibilities"},
    "mako": {"what you'll be doing", "what you'll be involved in"},
    "geneva_trading": {"the role", "how you can make an impact"},
    "da_vinci": {"responsibilities"},
    "qube_research": {"your future role within qrt", "responsibilities"},
    "man_group": {"role and responsibilities", "roles and responsibilities"},
    "totalenergies": {"activities", "responsibilities"},
    "engie": {
        "key responsibilities",
        "responsibilities",
        "your responsibilities as algorithmic trader",
        "your responsibilities as structurer",
        "what you can expect",
        "summary of what you will do",
    },
    "edf_trading": {"responsibilities", "main responsibilities"},
    "marex": {"responsibilities", "overall responsibilities"},
    "bp": set(),
    "shell": {"what you'll be doing"},
    "tp_icap": {"role responsibilities", "day-to-day responsibilities", "responsibilities"},
    "akuna_capital": {"in this role, you will"},
    "maven_securities": {"what you will be doing"},
    "point72": {"responsibilities", "role/responsibilities"},
    "virtu_financial": {"the role"},
    "tower_research": {"responsibilities"},
    "old_mission": {"responsibilities"},
    "schonfeld": {"what you'll do", "key responsibilities"},
    "five_rings": {"about the role"},
    "hudson_river_trading": {"responsibilities"},
    "transmarket_group": {"responsibilities"},
    "dv_trading": {"responsibilities", "responsibilities：", "job responsibilities"},
    "walleye_capital": {"responsibilities"},
    "squarepoint_capital": {
        "responsibilities",
        "key responsibilities",
        "role and responsibilities",
        "typical day of desk quant analyst",
        "typical day of quant researcher",
        "typical day",
    },
    "chicago_trading": {"what you'll do"},
    "chicago_trading_campus": {"responsibilities"},
    "belvedere_trading": {
        "what you'll do",
        "what our quantitative traders do",
        "what our quantitative trading interns do",
    },
}
