"""List headings audited on official finance employer boards."""

EMPLOYERS = {
    "tp_icap": "tp icap",
    "akuna_capital": "akuna capital",
    "maven_securities": "maven securities",
    "point72": "point72",
    "virtu_financial": "virtu financial",
    "tower_research": "tower research capital",
    "old_mission": "old mission",
    "schonfeld": "schonfeld",
    "five_rings": "five rings",
    "hudson_river_trading": "hudson river trading",
    "transmarket_group": "transmarket group",
    "dv_trading": "dv trading",
    "walleye_capital": "walleye capital",
    "squarepoint_capital": "squarepoint capital",
    "chicago_trading": "chicago trading company",
    "chicago_trading_campus": "chicago trading company",
    "belvedere_trading": "belvedere trading",
}
QUALIFICATIONS = {
    "bp": {"to be eligible for the stands graduate programme you should"},
    "shell": {"what you bring"},
    "tp_icap": {"essential", "desired"},
    "akuna_capital": {
        "qualities that make great candidates",
        "additional qualities that make great candidates",
    },
    "maven_securities": {"key criteria", "key requirements", "who you are"},
    "point72": {"requirements", "requirments", "desirable candidates"},
    "virtu_financial": {"the candidate", "requirements"},
    "tower_research": {"qualifications", "requirements", "preferred qualifications (not required)"},
    "old_mission": {"required skills", "required qualifications", "preferred qualifications"},
    "schonfeld": {"what you need", "required skills and qualifications", "we'd love if you had"},
    "five_rings": {"about you"},
    "hudson_river_trading": {"qualifications", "skills"},
    "transmarket_group": {"requirements"},
    "dv_trading": {"requirements", "requirements：", "preferred skills"},
    "walleye_capital": {"qualifications"},
    "squarepoint_capital": {
        "qualifications",
        "required qualifications",
        "preferred candidate profile",
        "nice to have",
    },
    "chicago_trading": {"what we're looking for", "nice to have", "nice to haves"},
    "chicago_trading_campus": {
        "qualifications",
        "key requirements",
        "what we're looking for",
        "what it takes for you to be successful",
        "nice to have",
    },
    "belvedere_trading": {"what you'll need", "key qualities in great candidates"},
}
RESPONSIBILITIES = {
    "bp": set(),
    "shell": {"what you'll be doing"},
    "tp_icap": {"role responsibilities", "day-to-day responsibilities", "responsibilities"},
    "akuna_capital": {"in this role, you will"},
    "maven_securities": {"what you will be doing"},
    "point72": {"responsibilities", "role/responsibilities"},
    "virtu_financial": {"the role"},
    "tower_research": {"responsibilities"},
    "old_mission": {"responsibilities"},
    "schonfeld": {"what you'll do", "key responsibilities"},
    "five_rings": {"about the role"},
    "hudson_river_trading": {"responsibilities"},
    "transmarket_group": {"responsibilities"},
    "dv_trading": {"responsibilities", "responsibilities：", "job responsibilities"},
    "walleye_capital": {"responsibilities"},
    "squarepoint_capital": {
        "responsibilities",
        "key responsibilities",
        "role and responsibilities",
        "typical day of desk quant analyst",
        "typical day of quant researcher",
        "typical day",
    },
    "chicago_trading": {"what you'll do"},
    "chicago_trading_campus": {"responsibilities"},
    "belvedere_trading": {
        "what you'll do",
        "what our quantitative traders do",
        "what our quantitative trading interns do",
    },
}
